# -*- coding: utf-8 -*-
"""cvipfinaltask1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14XnW9mZtECdbOkNmYCuYu-77rNRkFXkJ
"""



"""
Image Stitching Problem
(Due date: Nov. 26, 11:59 P.M., 2021)

The goal of this task is to stitch two images of overlap into one image.
You are given 'left.jpg' and 'right.jpg' for your image stitching code testing. 
Note that different left/right images might be used when grading your code. 

To this end, you need to find keypoints (points of interest) in the given left and right images.
Then, use proper feature descriptors to extract features for these keypoints. 
Next, you should match the keypoints in both images using the feature distance via KNN (k=2); 
cross-checking and ratio test might be helpful for feature matching. 
After this, you need to implement RANSAC algorithm to estimate homography matrix. 
(If you want to make your result reproducible, you can try and set fixed random seed)
At last, you can make a panorama, warp one image and stitch it to another one using the homography transform.
Note that your final panorama image should NOT be cropped or missing any region of left/right image. 

Do NOT modify the code provided to you.
You are allowed use APIs provided by numpy and opencv, except “cv2.findHomography()” and
APIs that have “stitch”, “Stitch”, “match” or “Match” in their names, e.g., “cv2.BFMatcher()” and
“cv2.Stitcher.create()”.
If you intend to use SIFT feature, make sure your OpenCV version is 3.4.2.17, see project2.pdf for details.
"""

import cv2
import numpy as np
# np.random.seed(<int>) # you can use this line to set the fixed random seed if you are using np.random
import random
# random.seed(<int>) # you can use this line to set the fixed random seed if you are using random
from cv2 import imread
import matplotlib.pyplot as plt
#from google.colab.patches import cv2_imshow
import random 
from random import sample
random.seed(4)

def solution(right_img, left_img):
    """
    :param left_img:
    :param right_img:
    :return: you need to return the result panorama image which is stitched by left_img and right_img
    """
    
    #left_img=imread(left_img)
    #cv2_imshow(left_img)
    #cv2_imshow(right_img)
    #cv2.waitKey(0)
    
    gray_left = cv2.cvtColor(left_img, cv2.COLOR_BGR2GRAY)
    gray_right = cv2.cvtColor(right_img, cv2.COLOR_BGR2GRAY)  
    
    
    #keypoints
    sift = cv2.SIFT_create()
    keypoints_leftimg, descriptors_leftimg = sift.detectAndCompute(gray_left, None)
    
    #left_img = cv2.drawKeypoints(gray_left, keypoints_leftimg, left_img)
    #plt.imshow(left_img)
                                                                    
    keypoints_rightimg, descriptors_rightimg = sift.detectAndCompute(gray_right, None)
      
    #right_img = cv2.drawKeypoints(gray_right, keypoints_rightimg, right_img)
    #plt.imshow(right_img)    

    keypts = [keypoints_leftimg, keypoints_rightimg]
    


    Match = BestMatch(descriptors_leftimg, descriptors_rightimg)
    #print(Match)
    l_matches = len(Match)
    #print(l_matches)

    homography_matrix =Ransac(keypoints_leftimg,keypoints_rightimg, Match, l_matches)
    #print(homography_matrix)
    
    return stitch(left_img, right_img, homography_matrix)

    



    
    # TO DO: implement your solution here
    #raise NotImplementedError
    #return result_img

def stitch(left_img, right_img, homography_matrix):
 
  image_frame = np.float32([[0, 0], [0, left_img.shape[0]], [left_img.shape[1], left_img.shape[0]], [left_img.shape[1], 0]]).reshape(-1, 1, 2)
  image_frame = cv2.perspectiveTransform(image_frame, homography_matrix)
  image_frame = cv2.warpPerspective(left_img, homography_matrix, ((right_img.shape[1] + left_img.shape[1]), right_img.shape[0]+left_img.shape[0]))
  image_frame[0:right_img.shape[0],0:right_img.shape[1]] = right_img
 
  return image_frame

def getDistance(a, b, m, n, h_2):
  A= np.matrix([[a],[b],[1]])
  B= np.matrix([[m],[n],[1]])
  tp = np.dot(h_2,A)
  tp1 = tp*(1/tp[2][0])
  dis = tp1 - B
  b = np.linalg.norm(dis)
  return b

def Ransac(keypoints_leftimg,keypoints_rightimg, Match, l_matches):
  maximum_inliers = 0
  final_H = []
  M= []
  array = np.zeros(shape=(8, 9), dtype=np.float64)
  for i in range(5000):
    random_sample = random.sample(Match,4)
    for j in range(0,4):
      a, b = keypoints_leftimg[random_sample[j].get("qIdx")].pt
      m, n = keypoints_rightimg[random_sample[j].get("tIdx")].pt
      r1=np.array([-a, -b, -1, 0, 0, 0, m*a, m*b, m])
      r2=np.array([0, 0, 0, -a, -b, -1, n*a, n*b, n])
      array[2*j] = r1
      array[(2*j) + 1] = r2
    u, s, vh = np.linalg.svd(array)    
    h_1= vh[np.argmin(s)].reshape(3, 3)
    inliers = 0
    for k in Match:
      x1, y1 = keypoints_leftimg[k.get("qIdx")].pt
      x2, y2 = keypoints_rightimg[k.get("tIdx")].pt
      distance = getDistance(x1, y1, x2, y2, h_1)
      if(distance< 5):
        inliers += 1
    if(inliers> maximum_inliers):
      maximum_inliers = inliers
      final_H = h_1
  
  return final_H

def BestMatch(descriptors_leftimg, descriptors_rightimg):
  
  m = len(descriptors_leftimg)
  n = len(descriptors_rightimg)
  match = []
  for i in range(m):
    descriptors_leftimg_C = descriptors_leftimg[i].reshape(-1,1)
    descriptors_leftimg_T= np.transpose(descriptors_leftimg_C)
    Calculate_distance = np.linalg.norm(descriptors_leftimg_T - descriptors_rightimg, axis =1)
    distance_sorted = np.sort(Calculate_distance)
    first_img_match, second_img_match = distance_sorted[0],distance_sorted[1]
    first_img_index, second_img_index = np.where(Calculate_distance ==first_img_match)[0][0],np.where(Calculate_distance ==second_img_match)[0][0]
    if first_img_match < .4*second_img_match:
      list = {"tIdx":first_img_index,"qIdx":i, "distance":first_img_match}
      match.append(list)

    
    
  
  return match

if __name__ == "__main__":
    left_img = cv2.imread('left.jpg')
    right_img = cv2.imread('right.jpg')
    result_img = solution(left_img, right_img)
    cv2.imwrite('/results/task1_result.jpg', result_img)





