# -*- coding: utf-8 -*-
"""cvipfinaltask2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1acSlgR8AHJkGV7zUW6H1aAqawGe216Ti
"""



"""
 Grayscale Image Processing
(Due date: Nov. 26, 11:59 P.M., 2021)

The goal of this task is to experiment with two commonly used 
image processing techniques: image denoising and edge detection. 
Specifically, you are given a grayscale image with salt-and-pepper noise, 
which is named 'task2.png' for your code testing. 
Note that different image might be used when grading your code. 

You are required to write programs to: 
(i) denoise the image using 3x3 median filter;
(ii) detect edges in the denoised image along both x and y directions using Sobel operators (provided in line 30-32).
(iii) design two 3x3 kernels and detect edges in the denoised image along both 45° and 135° diagonal directions.
Hint: 
• Zero-padding is needed before filtering or convolution. 
• Normalization is needed before saving edge images. You can normalize image using the following equation:
    normalized_img = 255 * frac{img - min(img)}{max(img) - min(img)}

Do NOT modify the code provided to you.
You are NOT allowed to use OpenCV library except the functions we already been imported from cv2. 
You are allowed to use Numpy for basic matrix calculations EXCEPT any function/operation related to convolution or correlation. 
You should NOT use any other libraries, which provide APIs for convolution/correlation ormedian filtering. 
Please write the convolution code ON YOUR OWN. 
"""
import cv2
from cv2 import imread, imwrite, imshow, IMREAD_GRAYSCALE, namedWindow, waitKey, destroyAllWindows
import numpy as np
#from google.colab.patches import cv2_imshow
import python_utils
# Sobel operators are given here, do NOT modify them.
sobel_x = np.array([[1, 0, -1], [2, 0, -2], [1, 0, -1]]).astype(int)
sobel_y = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]]).astype(int)

def filter(img):
    """
    :param img: numpy.ndarray(int), image
    :return denoise_img: numpy.ndarray(int), image, same size as the input image

    Apply 3x3 Median Filter and reduce salt-and-pepper noises in the input noise image
    """
    # TO DO: implement your solution here
    #cv2_imshow(img)
    image_data = np.array(img)
    #print(data.shape)

    filter_size = 3
    index = filter_size
    t = []
    final = []
    final = np.zeros((len(image_data), len(image_data[0])))
    #print(final.shape)
    m = len(image_data)
    n = len(image_data[0])

    for i in range(m):
      for j in range(n):
        for z in range(filter_size):
          if i + z - index < 0 or i + z - index > m - 1:
             for c in range(filter_size):
               t.append(0)
          else:
            if j + z - index < 0 or j + index > n - 1:
              t.append(0)
            else:
              for k in range(filter_size):
                t.append(image_data[i + z - index][j + k - index])

        t.sort()
        final[i][j] = t[len(t) // 2]
        t = []
    final = np.asarray(final) 
     
    #cv2_imshow(final)
    #data_final = denoise_img
    
    return final

def convolve2d(img, kernel):
    """
    :param img: numpy.ndarray, image
    :param kernel: numpy.ndarray, kernel
    :return conv_img: numpy.ndarray, image, same size as the input image

    Convolves a given image (or matrix) and a given kernel.
    """
    #print(img)
    #print(kernel)
    #print(img.shape)
    array = np.array(img)
    #padded_array = np.pad(array,((1,1),(1,1)),'constant')
    padded_array = array
    #print(padded_array)
    #print(padded_array.shape)

    flipped_kernal = np.flip(kernel)
    #print(flipped_kernal)

    padded_array_h = padded_array.shape[0]
    padded_array_w = padded_array.shape[1]
    flipped_kernal_h = flipped_kernal.shape[0]
    flipped_kernal_w = flipped_kernal.shape[1]
    h = flipped_kernal_h//2
    w = flipped_kernal_w//2

    con_img = np.zeros(padded_array.shape)
    for i in range(h, padded_array_h-h):
      for j in  range(h, padded_array_w-w):
        sum = 0
        for k in range(flipped_kernal_h):
          for l in range(flipped_kernal_w):
            sum = sum + flipped_kernal[k][l]*padded_array[i-h+k][j-w+l]
        con_img[i][j] =sum    
    con_img=np.asarray(con_img)
    #cv2_imshow(con_img)
    
    return con_img

def edge_detect(img):
    """
    :param img: numpy.ndarray(int), image
    :return edge_x: numpy.ndarray(int), image, same size as the input image, edges along x direction
    :return edge_y: numpy.ndarray(int), image, same size as the input image, edges along y direction
    :return edge_mag: numpy.ndarray(int), image, same size as the input image, 
                      magnitude of edges by combining edges along two orthogonal directions.

    Detect edges using Sobel kernel along x and y directions.
    Please use the Sobel operators provided in line 30-32.
    Calculate magnitude of edges by combining edges along two orthogonal directions.
    All returned images should be normalized to [0, 255].
    """
    #cv2_imshow(img)
    edge_x = convolve2d(img, sobel_x)
    edge_y = convolve2d(img, sobel_y)
    
    #print(edge_x.shape)

    #print(edge_y.shape)

    #edge_x = np.array(edge_x)
    #edge_y = np.array(edge_y)
    m = np.multiply(edge_x,edge_x)
    n  = np.multiply(edge_y,edge_y)
    #print(m)
    #print(n)

    sum =np.add(m,n)
    #print(sum)
    edgemag = np.sqrt(sum)
    #print(e)
    norm_img = np.zeros(edgemag.shape)
    ''' edge_mag = cv2.normalize(edgemag,  norm_img, 0, 255, cv2.NORM_MINMAX)
    normedgex_img = np.zeros(edge_x.shape)
    edge_x = cv2.normalize(edge_x,  normedgex_img, 0, 255, cv2.NORM_MINMAX)
    normedgey_img = np.zeros(edge_y.shape)
    edge_y = cv2.normalize(edge_y,  normedgey_img, 0, 255, cv2.NORM_MINMAX)'''
    edge_mag=norm_edge(edgemag)
    edge_x=norm_edge(edge_x)
    edge_y=norm_edge(edge_y)

    #cv2_imshow(edge_x)
    #cv2_imshow(edge_y)
    #cv2_imshow(edge_mag)
    
    # TO DO: implement your solution here
    #raise NotImplementedError
    return edge_x, edge_y, edge_mag

def norm_edge(edge):
   normedge = 255*((edge - np.min(edge))/(np.max(edge)-np.min(edge)))

   return normedge

def edge_diag(img):
    """
    :param img: numpy.ndarray(int), image
    :return edge_45: numpy.ndarray(int), image, same size as the input image, edges along x direction
    :return edge_135: numpy.ndarray(int), image, same size as the input image, edges along y direction

    Design two 3x3 kernels to detect the diagonal edges of input image. Please print out the kernels you designed.
    Detect diagonal edges along 45° and 135° diagonal directions using the kernels you designed.
    All returned images should be normalized to [0, 255].
    """

    egde45 = np.array([[-2,-1,0],
                       [-1, 0 ,1],
                       [0, 1, 2]])
    egde135 = np.array([[0,1,2],
                       [-1, 0 ,1],
                       [-2, -1, 0]])
    

    edge_45 = convolve2d(img, egde45)
    edge_135 = convolve2d(img, egde135)
    edge_45 = norm_edge(edge_45)
    edge_135 = norm_edge(edge_135)
    
    

    #cv2_imshow(edge_45)
    #cv2_imshow(edge_135)

    
    
    # TO DO: implement your solution here
    print() # print the two kernels you designed here
    return edge_45, edge_135

if __name__ == "__main__":
    noise_img = imread('task2.png', IMREAD_GRAYSCALE)
    denoise_img = filter(noise_img)
    imwrite('/results/task2_denoise.jpg', denoise_img)
    edge_x_img, edge_y_img, edge_mag_img = edge_detect(denoise_img)
    imwrite('/results/task2_edge_x.jpg', edge_x_img)
    imwrite('/results/task2_edge_y.jpg', edge_y_img)
    imwrite('/results/task2_edge_mag.jpg', edge_mag_img)
    edge_45_img, edge_135_img = edge_diag(denoise_img)
    imwrite('/results/task2_edge_diag1.jpg', edge_45_img)
    imwrite('/results/task2_edge_diag2.jpg', edge_135_img)



